### ISSUE TITLE
proses install

### ISSUE THREAD

**Issue by muhammadiqbalid83** [azzamsa/zman#9]
untuk install cukup ikuti instruksi aja kan mas? setelah itu dia langsung muncul di dekstop kan?

**Comment by azzamsa** [comment]
Kalau tidak punya cargo, pakai binary langsung saja https://github.com/azzamsa/zman#from-binaries

nanti tinggal `./zman` atau letakkan di $PATH.

**Comment by muhammadiqbalid83** [comment]
klo gitu saya coba dulu
